# Generated by Django 4.1.3 on 2022-11-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0007_book_book_id_alter_book_picture_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
    ]
