# Generated by Django 4.1.3 on 2022-11-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0008_remove_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
    ]
