# Generated by Django 4.1.3 on 2022-11-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
