# Generated by Django 4.1.3 on 2022-11-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0011_comment_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
